"""
Multi-Institution WEAMS-Approved Programs Module

This module contains the complete lists of WEAMS (Web-based Enrollment at Military
Institutions)-approved programs for multiple institutions:

- San Diego State University (SDSU): 531 programs, Facility Code 11910105
- California State University, Northridge (CSUN): 322 programs, Facility Code 11918105

Data scraped from the VA GI Bill Comparison Tool as of April 10, 2026.

The module provides utilities to match student-declared program names (from PeopleSoft
ACAD_PLAN descriptions) against the official WEAMS program lists, handling the format
differences between PeopleSoft and VA systems.

Source: VA GI Bill Comparison Tool (https://www.va.gov/gi-bill-comparison-tool/)
Data Retrieved: April 10, 2026
"""

from typing import Optional, Tuple
from difflib import SequenceMatcher

# Complete list of 531 WEAMS-approved programs for SDSU (Facility Code 11910105)
SDSU_WEAMS_PROGRAM_NAMES = [
    "ARTICULATION AGREEMENT FOR TRANSFER",
    "AUD AUDIOLOGY",
    "BA AFRICANA STUDIES",
    "BA AMERICAN INDIAN STUDIES",
    "BA ANTHROPOLOGY",
    "BA ART",
    "BA ART-APPLIED DESIGN",
    "BA ART-ART HISTORY",
    "BA ART-GRAPHIC DESIGN",
    "BA ART-INTERIOR ARCHITECTURE",
    "BA ART-MULTIMEDIA",
    "BA ART-PAINTING AND PRINTMAKING",
    "BA ART-SCULPTURE",
    "BA ART-STUDIO ARTS",
    "BA ASIAN AMERICAN STUDIES",
    "BA ASIAN STUDIES",
    "BA ASTRONOMY",
    "BA BIOLOGY",
    "BA BRAZILIAN STUDIES",
    "BA CHEMISTRY - AMERICAN CHEMICAL SOCIETY",
    "BA CHEMISTRY - APPLIED ARTS AND SCIENCES",
    "BA CHEMISTRY - LIBERAL ARTS AND SCIENCES",
    "BA CHICANA AND CHICANO STUDIES",
    "BA CLASSICS",
    "BA CLASSICS-CLASSICAL HUMANITIES",
    "BA CLASSICS-CLASSICAL LANGUAGE",
    "BA CLASSICS-CLASSICAL LANGUAGES HONORS",
    "BA COMMUNICATION - APPLIED ARTS SCIENCES",
    "BA COMMUNICATION - LIBERAL ARTS SCIENCES",
    "BA COMPARATIVE INTERNATIONAL STUDIES",
    "BA COMPARATIVE LITERATURE",
    "BA DANCE",
    "BA ECONOMICS",
    "BA ECONOMICS-INTERNATIONAL ECONOMICS",
    "BA ECONOMICS-PUBLIC POLICY",
    "BA ECONOMICS-QUANTITATIVE ANALYSIS",
    "BA ENGLISH AND COMP LIT PREP SINGLE SUB",
    "BA ENGLISH AND COMP LITERATURE - APPLIED",
    "BA ENGLISH AND COMP LITERATURE - LIBERAL",
    "BA EUROPEAN STUDIES",
    "BA FRENCH",
    "BA GEOGRAPHY-ENVIROMENT SUSTAIN AND POLI",
    "BA GEOGRAPHY-ENVIRONMENT SUSTAINABILITY",
    "BA GEOGRAPHY-GENERAL",
    "BA GEOGRAPHY-GIS AND TECHNOLOGY",
    "BA GEOGRAPHY-HUMAN GEOGRAPHY-GLOBAL STU",
    "BA GERMAN",
    "BA GERMAN-GERMAN STUDIES",
    "BA GERONTOLOGY",
    "BA HISTORY",
    "BA HUMANITIES",
    "BA HUMANITIES-GLOBAL HUMANITIES PROGRAM",
    "BA INTERDISCIPLINARY STUDIES THREE DEPTS",
    "BA INTERNATIONAL BUSINESS EURO LANG NORT",
    "BA INTERNATIONAL BUSINESS-ARABIC-MIDDLE",
    "BA INTERNATIONAL BUSINESS-ASIAN LANGUAGE",
    "BA INTERNATIONAL BUSINESS-CHINESE-ASIA",
    "BA INTERNATIONAL BUSINESS-ENGLISH-NORTH",
    "BA INTERNATIONAL BUSINESS-FRENCH-NORTH",
    "BA INTERNATIONAL BUSINESS-FRENCH-WESTER",
    "BA INTERNATIONAL BUSINESS-GERMAN-WESTER",
    "BA INTERNATIONAL BUSINESS-GLOBAL BUSINES",
    "BA INTERNATIONAL BUSINESS-ITALIAN-WESTE",
    "BA INTERNATIONAL BUSINESS-JAPANESE-ASIA",
    "BA INTERNATIONAL BUSINESS-KOREAN-ASIA",
    "BA INTERNATIONAL BUSINESS-PORTUGUESE-LA",
    "BA INTERNATIONAL BUSINESS-PORTUGUESE-WE",
    "BA INTERNATIONAL BUSINESS-RUSSIAN-CENTR",
    "BA INTERNATIONAL BUSINESS-SPANISH-LATIN",
    "BA INTERNATIONAL BUSINESS-SPANISH-WESTE",
    "BA ISCR - CONFLICT IN THE GLOBAL SYSTEM",
    "BA ISCR - ENVIRONMENT IN GLOBAL SYSTEM",
    "BA ISCR - JUSTICE IN THE GLOBAL SYSTEM",
    "BA ISLAMIC AND ARAB STUDIES",
    "BA JAPANESE",
    "BA JOURNALISM",
    "BA JOURNALISM-ADVERTISING",
    "BA JOURNALISM-MEDIA STUDIES",
    "BA JOURNALISM-PUBLIC RELATIONS",
    "BA LANGUAGE CULTURE AND SOCIETY",
    "BA LATIN AMERICAN STUDIES",
    "BA LESBIAN GAY BISEXUAL TRANSGENDER QUEE",
    "BA LIBERAL STUDIES",
    "BA LIBERAL STUDIES-EDUCATION GENERALIST",
    "BA LIBERAL STUDIES-ELEMENTARY EDUCATION",
    "BA LIBERAL STUDIES-MATHEMATICS",
    "BA LIBERAL STUDIES-SCIENCE",
    "BA LINGUISTICS",
    "BA MATHEMATICS",
    "BA MATHEMATICS-PREP SS TEACHING CREDENT",
    "BA MICROBIOLOGY",
    "BA MODERN JEWISH STUDIES",
    "BA MUSIC",
    "BA PHILOSOPHY",
    "BA PHYSICAL SCIENCE",
    "BA PHYSICS",
    "BA POLITICAL SCIENCE",
    "BA PSYCHOLOGY",
    "BA PSYCHOLOGY - APPLIED ARTS AND SCIENCE",
    "BA PSYCHOLOGY-INDUSTRIAL-ORGANIZATIONAL",
    "BA PSYCHOLOGY-NEUROSCIENCE",
    "BA PUBLIC ADMINISTRATION",
    "BA PUBLIC ADMINISTRATION-CITY PLANNING",
    "BA RELIGIOUS STUDIES",
    "BA RHETORIC AND WRITING STUDIES",
    "BA RUSSIAN",
    "BA RUSSIAN AND CENTRAL EUROPEAN STUDIES",
    "BA RUSSIAN-PREP SS TEACHING CREDENTIAL",
    "BA SOCIAL SCIENCE",
    "BA SOCIAL SCIENCE-PREP SS TEACHING CRED",
    "BA SOCIAL WORK",
    "BA SOCIAL WORK-COMMUNITY CORRECTIONS",
    "BA SOCIAL WORK-ENVIRONMENTAL SOCIAL",
    "BA SOCIOLOGY",
    "BA SPANISH",
    "BA SPANISH-SINGLE SUBJECT TEACHING",
    "BA SPEECH LANGUAGE AND HEARING SCIENCES",
    "BA SUSTAINABILITY",
    "BA THEATRE ARTS",
    "BA THEATRE ARTS-DESIGN AND TECHNOLOGY",
    "BA THEATRE ARTS-GENERAL THEATRE ARTS",
    "BA THEATRE ARTS-PERFORMENCE",
    "BA THEATRE ARTS-YOUTH THEATRE",
    "BA URBAN STUDIES",
    "BA URBAN STUDIES-POLITICAL ECONOMY",
    "BA URBAN STUDIES-URBAN CULTURES AND SOC",
    "BA URBAN STUDIES-URBAN PLANNING DESIGN",
    "BA URBAN STUDIES-URBAN SUSTAINABILITY",
    "BA WOMENS STUDIES",
    "BFA DANCE",
    "BFA DANCE-DANCE EDUCATION",
    "BM MUSIC-GENERAL TRACK",
    "BM MUSIC-GLOBAL COMPOSITION",
    "BM MUSIC-JAZZ STUDIES",
    "BM MUSIC-MUSIC EDUCATION",
    "BM MUSIC-MUSIC ENTREPRENEUR-BUSINESS",
    "BM MUSIC-MUSIC RECORDING TECH AND AUDIO",
    "BM MUSIC-PERFORMANCE",
    "BS AEROSPACE ENGINEERING",
    "BS ARTIFICIAL INTELLIGENCE AND HUMAN RES",
    "BS ASTRONOMY",
    "BS ATHLETIC TRAINING",
    "BS BIOLOGY",
    "BS BIOLOGY- SINGLE SUBJECT TEACHING CRED",
    "BS BIOLOGY-CELLULAR-MOLECULAR BIOLOGY",
    "BS BIOLOGY-ECOLOGY",
    "BS BIOLOGY-EVOLUTIONARY BIOLOGY",
    "BS BIOLOGY-MARINE BIOLOGY",
    "BS BIOLOGY-ZOOLOGY",
    "BS BUSINESS ADMIN-ACCOUNTING",
    "BS BUSINESS ADMIN-FINANCE",
    "BS BUSINESS ADMIN-FINANCIAL SERVICES",
    "BS BUSINESS ADMIN-GENERAL BUSINESS",
    "BS BUSINESS ADMIN-INFORMATION SYSTEMS",
    "BS BUSINESS ADMIN-MANAGEMENT",
    "BS BUSINESS ADMIN-MANAGEMENT-ENTREPRENE",
    "BS BUSINESS ADMIN-MANAGEMENT-HUMAN RESO",
    "BS BUSINESS ADMIN-MARKETING GENERAL MAR",
    "BS BUSINESS ADMIN-MARKETING INTEGRATED",
    "BS BUSINESS ADMIN-MARKETING PROFESSIONA",
    "BS BUSINESS ADMIN-REAL ESTATE",
    "BS CHEMICAL PHYSICS",
    "BS CHEMISTRY",
    "BS CHEMISTRY-BIOCHEMISTRY",
    "BS CIVIL ENGINEERING",
    "BS COMPUTER ENGINEERING",
    "BS COMPUTER SCIENCE",
    "BS CONSTRUCTION ENGINEERING",
    "BS CONSTRUCTION MANAGEMENT",
    "BS CRIMINAL JUSTICE",
    "BS ELECTRICAL ENGINEERING",
    "BS ENVIRONMENTAL ENGINEERING",
    "BS ENVIRONMENTAL SCIENCES",
    "BS FOODS AND NUTRITION",
    "BS GEOGRAPHY-GIS AND TECHNOLOGY",
    "BS GEOGRAPHY-WATER CLIMATE-ECOSYSTEMS",
    "BS GEOLOGICAL SCIENCES",
    "BS GEOLOGICAL SCIENCES-ENGINEERING GEOG",
    "BS GEOLOGICAL SCIENCES-ENVIRONMENTAL GE",
    "BS GEOLOGICAL SCIENCES-GENERAL GEOLOGY",
    "BS GEOLOGICAL SCIENCES-GEOPHYSICS",
    "BS GEOLOGICAL SCIENCES-HYDROGEOLOGY",
    "BS GEOLOGICAL SCIENCES-PALEONTOLOGY",
    "BS HEALTH COMMUNICATION",
    "BS HOSPITALITY-TOURISM MANAGEMENT-HTM",
    "BS HTM-HOTEL OPERATIONS AND MANAGEMENT",
    "BS HTM-MEETINGS-EVENTS OPERATIONS AND M",
    "BS HTM-RESTAURANT OPERATIONS AND MANAGE",
    "BS HTM-TRIBAL GAMING OPERATIONS AND MAN",
    "BS KINESIOLOGY-EXERCISE SCIENCE GENERAL",
    "BS KINESIOLOGY-FITNESS SPECIALIST",
    "BS KINESIOLOGY-PREPHYSICAL THERAPY",
    "BS LEADERSHIP STUDIES",
    "BS MATHEMATICS",
    "BS MATHEMATICS-APPLIED MATHEMATICS",
    "BS MATHEMATICS-COMPUTATIONAL SCIENCE",
    "BS MATHEMATICS-MATHEMATICS EDUCATION",
    "BS MATHEMATICS-SCIENCE",
    "BS MECHANICAL ENGINEERING",
    "BS MECHANICAL ENGINEERING-BIOENGINEERIN",
    "BS MICROBIOLOGY",
    "BS MICROBIOLOGY-CLINICAL LABORATORY SCI",
    "BS MS 4 PLUS 1 ACCOUNTING",
    "BS MS MECHANICAL ENGINEERING-BIOENGINEER",
    "BS MS MECHNAICAL ENGINEERING 4 PLUS 1",
    "BS NURSING",
    "BS NURSING-REGISTERED NURSE",
    "BS PHYSICS",
    "BS PHYSICS-MODERN OPTICS",
    "BS PUBLIC HEALTH",
    "BS PUBLIC HEALTH-ENVIRONMENTAL HEALTH",
    "BS RECREATION ADMINISTRATION",
    "BS RECREATION ADMINISTRATION-OUTDOOR RE",
    "BS RECREATION ADMINISTRATION-RECREATION",
    "BS RECREATION ADMINISTRATION-SUSTAINABL",
    "BS STATISTICS",
    "BS STATISTICS-ACTUARIAL SCIENCE",
    "BS STATISTICS-DATA SCIENCE",
    "BS TV FILM-NEW MEDIA-CRITICAL STUDIES",
    "BS TV FILM-NEW MEDIA-PRODUCTION",
    "DNP NURSING",
    "DPT PHYSICAL THERAPY",
    "DrPH PUBLIC HEALTH-EXECUTIVE MANAGMENT",
    "DrPH PUBLIC HEALTH-GLOBAL HEALTH MNGMT",
    "EDD EDUCATIONAL LEADERSHIP-COMMUNITY",
    "EDD EDUCATIONAL LEADERSHIP-PRE K-12",
    "EDS SCHOOL PSYCHOLOGY",
    "GC ADVANCED CLINICAL CONTENT PEDIATRIC",
    "GC ADVANCED CLINICAL CONTENT-ADULT HEALT",
    "GC ADVANCED CLINICAL CONTENT-MATERNAL",
    "GC APPLIED GERONTOLOGY",
    "GC ARTIST DIPLOMA ADVANCED",
    "GC BEHAVIOR ANALYSIS ADVANCED",
    "GC BILINGUAL ADDED AUTH BILITERACY K-12",
    "GC BILINGUAL SPANISH 2042 MULTI SUB-SPED",
    "GC BILINGUAL SPEECH-LANGUAGE PATHOLOGY",
    "GC BIOMEDICAL QUALITY SYSTEMS",
    "GC CHILDRENS ADOLESCENT LITERATURE ADV",
    "GC CLEAR ADMINISTRATIVE SERVICES CRED",
    "GC CO-OCCURING DISORDERS ADVANCED",
    "GC COGNITIVE DISABILITIES",
    "GC COMMUNICATION SYSTEMS",
    "GC COMMUNITY COLLEGE TEACHING",
    "GC COMPARATIVE AND GLOBAL POLITICS",
    "GC CYBERSECURITY MANAGEMENT",
    "GC DATA ANALYTICS",
    "GC DATA SCIENCE",
    "GC DEVELOPING GIFTED POTENTIAL",
    "GC DISTANCE EDUCATION",
    "GC DUAL LANGUAGE FOR ACADEMIC LITERACY",
    "GC EARLY CARE AND EDUCATION",
    "GC EARLY CHILDHOOD SPECIAL EDUCATION ADD",
    "GC EARLY CHILDHOOD SPED-MILD TO MODERATE",
    "GC EARLY CHILDHOOD TRANSDISCIPLINARY EDU",
    "GC EDU SPEC IN SPED-MILD TO MODERATE DIS",
    "GC EDUCATIONAL LEADERSHIP IN INTCLG ATH",
    "GC ELEMENTARY K-6 ED MULTI-SUB BILINGUAL",
    "GC ENGLISH LANGUAGE DEV FOR ACADEMIC LIT",
    "GC ENTERTAINMENT MANAGEMENT",
    "GC ENTREPRENEURSHIP",
    "GC ENVIRONMENTAL STUDIES",
    "GC EXECUTIVE FINANCIAL PLANNER",
    "GC FEMINIST STUDIES ADVANCED CERTIFICATE",
    "GC FINANCIAL ANALYSIS",
    "GC INDUCTION PROGRAM MULTI-SING SUB CRED",
    "GC INSTRUCTIONAL DESIGN",
    "GC INSTRUCTIONAL TECHNOLOGY",
    "GC INTELLECTUAL PROPERTY AND REGULATORY",
    "GC INVESTMENT",
    "GC K12 ETHNIC STUDIES TEACHING",
    "GC LANGUAGE SPEEACH AND HEARING SLP CRED",
    "GC MEETING AND EVENT MANAGEMENT",
    "GC MULTI AND SING SUBJECT PROF CLR TEACH",
    "GC MULTI SUBJ 2042 CRED ELEMENTARY EDU",
    "GC MULTI SUBJ BILINGUAL 2042 CREDENTIAL",
    "GC PRELIMINARY ADMINISTRATIVE SERVICES",
    "GC PREVENTIVE MEDICINE RESIDENCY",
    "GC PROFESSIONAL COMPUTATIONAL SCIENCE",
    "GC PSYCHIATRIC REHABILITATION",
    "GC PUBLIC HEALTH",
    "GC PUBLIC POLICY",
    "GC PUPIL PERSONNEL SERVICES",
    "GC READING AND LITERACY LEADERSHIP SPEC",
    "GC REGULATORY AFFAIRS",
    "GC REHABILITATION ADMINISTRATION",
    "GC REHABILITATION COUNSELING",
    "GC REHABILITATION TECHNOLOGY",
    "GC RESIDENCY TRAINING IN RADIATION",
    "GC RESTORATIVE JUSTICE PRACTICE TRAUMA",
    "GC SECONDARY EDU GRADE 6-12 SS BILINGUAL",
    "GC SECONDARY EDUCATION SING SUB CRED",
    "GC SINGLE SUBJ BILINGUAL 2042 CREDENTIAL",
    "GC SINGLE SUBJ BILINGUAL 2042 SECOND EDU",
    "GC SINGLE SUBJECT MATHEMATICS",
    "GC SOCIAL WORK ADMINISTRATION",
    "GC SUPPORTED EMPLOYMENT-SUPPORTED SPEC",
    "GC TAXATION",
    "GC TEACHING OF WRITING",
    "GC TESL OR TEFL",
    "GC WEB AND MOBILE APPLICATIONS DEVELOPME",
    "GC WORKFORCE EDUCATION-LIFELONG LEARNING",
    "MA ANTHROPOLOGY",
    "MA ART-ART HISTORY",
    "MA ART-STUDIO ART",
    "MA BIOLOGY",
    "MA BIOLOGY-ECOLOGY",
    "MA BIOLOGY-EVOLUTIONARY BIOLOGY",
    "MA BIOLOGY-MOLECULAR BIOLOGY",
    "MA BIOLOGY-PHYSIOLOGY",
    "MA CHEMISTRY",
    "MA CHICANA AND CHICANO STUDIES",
    "MA COMMUNICATION",
    "MA COMMUNICATION-MASS COMMUNICATION",
    "MA DUAL LANG ENG LEARN CRIT LIT SOC JUST",
    "MA ECONOMICS",
    "MA EDU-DUAL LANGUAGE-ENGLISH LEARNER",
    "MA EDU-EDUCATIONAL LEADERSHIP-POSTSECON",
    "MA EDU-EDUCATIONAL LEADERSHIP-PRE K-12",
    "MA EDU-ELEMENTARY CURRICULUM AND INSTR.",
    "MA EDU-MATHEMATICS EDUCATION K-8",
    "MA EDU-READING EDUCATION",
    "MA EDU-SEC CURRICULUM AND INSTRUCTION",
    "MA EDU-SPECIAL EDUCATION",
    "MA EDU-SPECIAL EDUCATION-AUTISM",
    "MA EDU-SPECIAL EDUCATION-EARLY CHILDHOO",
    "MA EDU-SPECIAL EDUCATION-MILD MODERATE",
    "MA EDUCATION-COUNSELING",
    "MA EDUCATION-DUAL LANG ENG LEARN OUT",
    "MA EDUCATION-SPECIAL EDUCATION EXTENSIVE",
    "MA EDUCATIONAL LEADERSHIP",
    "MA EDUCATIONAL LEADERSHIP OPASC COMBO",
    "MA ENGINEERING",
    "MA ENGLISH",
    "MA FEMINIST STUDIES",
    "MA FRENCH",
    "MA GEOGRAPHY",
    "MA HISTORY",
    "MA HISTORY-WAR AND SOCIETY STUDIES",
    "MA INTERDISCIPLINARY STUDIES",
    "MA LATIN AMERICAN STUDIES",
    "MA LEARNING DESIGN AND TECHNOLOGY",
    "MA LIBERAL ARTS AND SCIENCES",
    "MA LINGUISTICS",
    "MA LINGUISTICS-TESOL APPLIED LINGUISTICS",
    "MA MASS COMMUNICATION",
    "MA MATHEMATICS",
    "MA MATHEMATICS AND SCIENCE EDUCATION",
    "MA MOLECULAR BIOLOGY",
    "MA MUSIC",
    "MA MUSIC-MUSIC THEORY",
    "MA MUSIC-MUSICOLOGY",
    "MA MUSIC-PIANO PEDAGOGY",
    "MA PHILOSOPHY",
    "MA PHYSICS",
    "MA POLITICAL SCIENCE-GENERAL",
    "MA POLITICAL SCIENCE-INTERNATIONAL",
    "MA POLITICAL SCIENCE-PUBLIC POLICY",
    "MA POSTSEC EDUCA LEADERSHP AND STU AFFAI",
    "MA PSYCHOLOGY",
    "MA RHETORIC AND WRITING STUDIES",
    "MA RHETORIC AND WRITING STUDIES-PROFESS",
    "MA RHETORIC AND WRITING STUDIES-TEACH",
    "MA SOCIOLOGY",
    "MA SPANISH",
    "MA SPEECH LANGUAGE AND HEARING SCIENCES",
    "MA SPEECH LANGUAGE-HEARING-COMMUNCATIVE",
    "MA SPEECH LANGUAGE-HEARING-SPL",
    "MA SPEECH LANGUAGE-HEARING-SPL-BILINGUA",
    "MA TEACHER LEADERSHIP",
    "MA TEACHING",
    "MA TEACHING SERVICE-MATHEMATICS",
    "MA TEACHING SERVICE-MATHEMATICS-COMMUNI",
    "MA TEACHING SERVICE-MATHEMATICS-SECONDA",
    "MA THEATRE ARTS",
    "MAT TEACHING-ELEMENTARY EDUCATION",
    "MAT TEACHING-LANGUAGE ARTS EDUCATION",
    "MAT TEACHING-MATHEMATICS EDUCATION K-8",
    "MAT TEACHING-READING EDUCATION",
    "MAT TEACHING-SCIENCE EDUCATION",
    "MAT TEACHING-SECONDARY EDUCATION",
    "MBA BUSINESS ADMINISTRATION",
    "MBA BUSINESS ADMINISTRATION-EXECUTIVES",
    "MBA BUSINESS ADMINISTRATION-SPORTS BUSI",
    "MBA JD BUSINESS ADMIN AND LAW CAL WEST",
    "MBA JD BUSINESS ADMIN AND LAW THOM JEFF",
    "MBA MA BUSINESS ADMIN AND LATIN AMERICAN",
    "MCP CITY PLANNING",
    "MENG MASTER OF ENGINEERING",
    "MFA ART",
    "MFA CREATIVE WRITING",
    "MFA FILM AND TELEVISION PRODUCTION",
    "MFA MUSICAL THEATRE",
    "MFA SCREEN WRITING",
    "MFA THEATRE ARTS",
    "MFA THEATRE ARTS-ACTING",
    "MFA THEATRE ARTS-DESIGN AND TECHNOLOGY",
    "MFA THEATRE ARTS-MUSICAL THEATRE",
    "MM MUSIC",
    "MM MUSIC EDUCATION",
    "MM MUSIC-CONDUCTING",
    "MM MUSIC-GLOBAL COMPOSITION",
    "MM MUSIC-JAZZ STUDIES",
    "MM MUSIC-PERFORMANCE",
    "MPA PUBLIC ADMINISTRATION",
    "MPA PUBLIC ADMINISTRATION-CITY PLANNING",
    "MPA PUBLIC ADMINISTRATION-CRIMINAL",
    "MPA-JD PUBLIC ADMINISTRATION-JURIS DOCTO",
    "MPA-MA LATIN AMERICAN STUDIES",
    "MPH BIOLOGY - MICROBIOLOGY",
    "MPH PUBLIC HEALTH",
    "MPH PUBLIC HEALTH-BIOMETRY",
    "MPH PUBLIC HEALTH-ENVIRONMENTAL HEALTH",
    "MPH PUBLIC HEALTH-EPIDEMIOLOGY",
    "MPH PUBLIC HEALTH-GLOBAL HEALTH HUM CENT",
    "MPH PUBLIC HEALTH-HEALTH MANAGEMENT",
    "MPH PUBLIC HEALTH-HEALTH PROMOTION",
    "MPH-MA LATIN AMERICAN STUDIES",
    "MPH-MA PUBLIC HEALTH ENV HEALTH LATIN AM",
    "MPH-MA PUBLIC HEALTH EPIDEMIOLOGY LATIN",
    "MPH-MA PUBLIC HEALTH PROMO BEH SCI LATIN",
    "MS ACCOUNTANCY",
    "MS AEROSPACE ENGINEERING",
    "MS APPLIED MATHEMATICS",
    "MS APPLIED MATHEMATICS-DYNAMICAL SYSTEM",
    "MS ASTRONOMY",
    "MS ATHLETIC TRAINING",
    "MS BIG DATA ANALYTICS",
    "MS BIOENGINEERING",
    "MS BIOINFORMATICS-MEDICAL INFORMATICS",
    "MS BIOINFORMATICS-MEDICAL INFORMATICS-PS",
    "MS BIOLOGY",
    "MS BIOLOGY-ECOLOGY",
    "MS BIOLOGY-EVOLUTIONARY BIOLOGY",
    "MS BIOLOGY-MICROBIOLOGY",
    "MS BIOLOGY-MOLECULAR BIOLOGY",
    "MS BIOLOGY-PHYSIOLOGY",
    "MS BUSINESS ADMINISTRATION",
    "MS BUSINESS ADMINISTRATION-FINANCIAL",
    "MS CHEMISTRY",
    "MS CHILD AND FAMILY DEVELOPMENT",
    "MS CHILD DEVELOPMENT",
    "MS CHILD DEVELOPMENT-EARLY CHILDHOOD",
    "MS CIVIL ENGINEERING",
    "MS CIVIL ENGINEERING-ENVIRONMENTAL ENGI",
    "MS COMPUTATIONAL SCIENCE",
    "MS COMPUTATIONAL SCIENCE-DATA SCIENCE",
    "MS COMPUTATIONAL SCIENCE-PROFESSIONAL",
    "MS COMPUTER ENGINEERING",
    "MS COMPUTER SCIENCE",
    "MS COUNSELING",
    "MS COUNSELING-MARRIAGE-FAMILY THERAPY",
    "MS COUNSELING-MULTICULTURAL COMMUNITY",
    "MS COUNSELING-SCHOOL COUNSELING",
    "MS COUNSELING-SCHOOL PSYCHOLOGY",
    "MS CRIMINAL JUSTICE AND CRIMINOLOGY",
    "MS CYBERSESCURITY MANAGEMENT",
    "MS ELECTRICAL ENGINEERING",
    "MS ENVIRONMENTAL ENGINEERING",
    "MS EPIDEMIOLOGY",
    "MS EXERCISE PHYSIOLOGY",
    "MS FINANCE",
    "MS FINANCIAL AND TAX PLANNING",
    "MS FOOD SCIENCE",
    "MS GEOGRAPHY",
    "MS GEOGRAPHY-GEOGRAPHIC INFORMATION",
    "MS GEOGRAPHY-WATERSHED SCIENCE",
    "MS GEOLOGICAL SCIENCES",
    "MS GEOLOGICAL SCIENCES-GEOPHYSICS",
    "MS GERONTOLOGY",
    "MS GLOBAL BUSINESS DEVELOPMENT",
    "MS HOMELAND SECURITY",
    "MS HOSPITALITY AND TOURISM MANAGEMENT",
    "MS INFORMATION SYSTEMS",
    "MS INTERDISCIPLINARY STUDIES",
    "MS KINESIOLOGY",
    "MS MECHANICAL ENGINEERING",
    "MS MECHANICAL ENGINEERING-DESIGN",
    "MS MECHANICAL ENGINEERING-DYNAMICS",
    "MS MECHANICAL ENGINEERING-ENERGY",
    "MS MECHANICAL ENGINEERING-MATERIALS",
    "MS MEDICAL PHYSICS",
    "MS MEETING AND EVENT MANAGEMENT",
    "MS MICROBIOLOGY",
    "MS MOLECULAR BIOLOGY",
    "MS MS NUTRITIONAL SCIENCES AND EXCERCISE",
    "MS NURSE PRACTIONER AND CLINICAL NURSE",
    "MS NURSING",
    "MS NURSING-ADVANCED PRACTICE NURSING",
    "MS NURSING-NURSING LEADERSHIP",
    "MS NUTRITIONAL SCIENCES",
    "MS PHYSICS",
    "MS PSYCHOLOGY",
    "MS PSYCHOLOGY-AP-INDUSTRIAL-ORGANIZATIO",
    "MS PSYCHOLOGY-AP-QUANTITATIVE METHODS",
    "MS PSYCHOLOGY-CLINICAL PSYCHOLOGY",
    "MS PUBLIC HEALTH",
    "MS PUBLIC HEALTH-ENVIRONMENTAL HEALTH",
    "MS REGULATORY AFFAIRS",
    "MS REHABILITATION COUNSELING",
    "MS REHABILITATION COUNSELING-CLINICAL",
    "MS SCHOOL COUNSELING",
    "MS SCHOOL PSYCHOLOGY",
    "MS STATISTICS",
    "MS STATISTICS-BIOSTATISTICS",
    "MSW JD SOCIAL WORK-JURIS DOCTOR",
    "MSW MPH SOCIAL WORK-PUBLIC HEALTH",
    "MSW SOCIAL WORK ADMINISTRATION COMM ADV",
    "MSW SOCIAL WORK-ADMINISTRATION-COMMUNIT",
    "MSW SOCIAL WORK-DIRECT PRACTICE",
    "MSW SOCIAL WORK-DIRECT PRACTICE ADV",
    "MULTI BS CHILD DEVELOPMENT-ITEP",
    "PHD BIOLOGY",
    "PHD CHEMISTRY",
    "PHD CLINICAL PSYCHOLOGY",
    "PHD COMPUTATIONAL SCIENCE",
    "PHD ECOLOGY",
    "PHD EDUCATION",
    "PHD ENGINEERING SCIENCES-BIOENGINEERING",
    "PHD ENGINEERING SCIENCES-ELECT AND COMP",
    "PHD ENGINEERING SCIENCES-MECH AND AEROSP",
    "PHD ENGINEERING SCIENCES-STRUCTURAL ENGI",
    "PHD EVOLUTIONARY BIOLOGY",
    "PHD GEOGRAPHY",
    "PHD GEOPHYSICS",
    "PHD INTERDISCIPLINARY RESEARCH SUBSTANCE",
    "PHD LANGUAGE-COMMUNICATIVE DISORDERS",
    "PHD MATHEMATICS EDUCATION",
    "PHD PUBLIC HEALTH HEALTH BEHAVIOR HUMAN",
    "PHD PUBLIC HEALTH-EPIDEMIOLOGY",
    "PHD PUBLIC HEALTH-GLOBAL HEALTH",
    "PHD PUBLIC HEALTH-HEALTH BEHAVIOR",
]

# Complete list of 322 WEAMS-approved programs for CSUN (Facility Code 11918105)
CSUN_WEAMS_PROGRAM_NAMES = [
    "ARTICULATION AGREEMENT FOR TRANSFER",
    "AUD AUDIOLOGY",
    "BA AFRICAN AND AFRICAN AMERICAN-SOC SCI",
    "BA AFRICAN AND AFRICAN-AMERICAN-HUM CULT",
    "BA AFRICAN-AMERICAN URBAN EDUCATION",
    "BA ANTHROPOLOGY",
    "BA ART",
    "BA ASIAN AMERICAN STUDIES DOUBLE MAJOR",
    "BA ASIAN AMERICAN STUDIES STANDARD",
    "BA BIOLOGY",
    "BA CENTRAL AMERICAN STUDIES DOUBLE MAJOR",
    "BA CENTRAL AMERICAN STUDIES STANDARD",
    "BA CHEMISTRY",
    "BA CHICANO AND CHICANA STUDIES DOUBLE",
    "BA CHICANO AND CHICANA STUDIES SINGLE",
    "BA CHICANO AND CHICANA STUDIES SOC SCI",
    "BA CHILD ADOLESCENT DEV-APPLIED DEV SCI",
    "BA CHILD ADOLESCENT DEV-EARLY CHILDHOOD",
    "BA CHILD ADOLESCENT DEV-HONOR",
    "BA CINEMA AND TV ARTS-EMERGING MEDIA PRO",
    "BA CINEMA AND TV ARTS-ENTERTAIN MEDIA MA",
    "BA CINEMA AND TV ARTS-FILM PRODUCTION",
    "BA CINEMA AND TV ARTS-MEDIA THEORY CRIT",
    "BA CINEMA AND TV ARTS-SCREENWRITING",
    "BA CINEMA AND TV ARTS-TELEVISION PRODUCT",
    "BA COMMUNICATION STUDIES",
    "BA COMMUNICATIVE DISORDER",
    "BA CRIMINOLOGY AND JUSTICE STUDIES",
    "BA DANCE",
    "BA DEAF STUDIES",
    "BA ECONOMICS",
    "BA ENGLISH CREATIVE WRITING",
    "BA ENGLISH FOUR YEAR INTEGRATED SSC",
    "BA ENGLISH HONORS",
    "BA ENGLISH JUNIOR YEAR INTEGRATED SSC",
    "BA ENGLISH SUBJECT MATTER PROGRAM SSC",
    "BA ENGLISH-LITERATURE",
    "BA ENVIORMENTAL SCIENCE",
    "BA GENDER AND WOMENS STUDIES",
    "BA GENDER AND WOMENS STUDIES-DOUBLE MAJ",
    "BA HISTORY",
    "BA HISTORY-FYI ENGLISH SSC",
    "BA HISTORY-JYI ENGLISH SSC",
    "BA INTERDISCIPLINARY STUDIES",
    "BA JEWISH STUDIES",
    "BA JOURNALISM",
    "BA JOURNALISM BROADCAST",
    "BA JOURNALISM PUBLIC RELATIONS",
    "BA LANGUAGES AND CULTURES-ARMENIAN",
    "BA LANGUAGES AND CULTURES-FRENCH",
    "BA LANGUAGES AND CULTURES-ITALIAN",
    "BA LANGUAGES AND CULTURES-JAPANESE",
    "BA LIBERAL STUDIES ITEP FRESHMAN",
    "BA LIBERAL STUDIES ITEP JUNIOR",
    "BA LIBERAL STUDIES PRE-CREDENTIAL PROG",
    "BA LINGUISTICS",
    "BA MATHEMATICS",
    "BA MATHEMATICS SECONDARY TEACHING",
    "BA MATHEMATICS-FYI ENGLISH SSC",
    "BA MATHEMATICS-JYI ENGLISH SSC",
    "BA MUSIC - PRE TEACHING OPTION",
    "BA MUSIC-BREADTH STUDIES",
    "BA MUSIC-MUSIC EDUCATION",
    "BA MUSIC-MUSIC INDUSTRY STUDIES",
    "BA MUSIC-MUSIC THERAPY",
    "BA PHILOSOPHY",
    "BA PHILOSOPHY DOUBLE MAJOR",
    "BA PHYSICS",
    "BA POLITICAL SCIENCE-LAW AND SOCIETY",
    "BA POLITICAL SCIENCE-POLITICS AND GOVERN",
    "BA POLITICAL SCIENCE-PUBLIC POLICY MNGT",
    "BA PSYCHOLOGY",
    "BA PSYCHOLOGY-HONORS",
    "BA PUBLIC SECTOR MANAGEMENT",
    "BA REIGIOUS STUDIES",
    "BA RELIGIOUS STUDIES DOUBLE MAJOR",
    "BA SOCIOLOGY",
    "BA SPANISH-HISPANIC LINGUISTICS",
    "BA SPANISH-LANGUAGE AND CULTURE",
    "BA SPANISH-LITERATURE",
    "BA SPANISH-TRANSLATION AND INTERPRET",
    "BA THEATRE",
    "BA URBAN STUDIES AND PLANNING",
    "BM MUSIC-COMP COMMERCIAL AND MEDIA WRIT",
    "BM MUSIC-JAZZ STUDIES",
    "BM MUSIC-KEYBOARD",
    "BM MUSIC-PERCUSSION",
    "BM MUSIC-STRING",
    "BM MUSIC-VOCAL ARTS",
    "BM MUSIC-WINDS",
    "BS ACCOUNTANCY-INFORMATION SYSTEMS",
    "BS ACCOUNTANCY-PROFESSIONAL ACCOUNTANCY",
    "BS ATHLETIC TRAINING",
    "BS BIOCHEMISTRY",
    "BS BIOTECHNOLOGY MEDICAL TECHNOLOGY",
    "BS BUSINESS ADMIN-BUSINESS LAW",
    "BS BUSINESS ADMIN-FINANCIAL ANALYSIS",
    "BS BUSINESS ADMIN-FINANCIAL PLANNING",
    "BS BUSINESS ADMIN-GLOBAL SUPPLY CHAIN",
    "BS BUSINESS ADMIN-MANAGEMENT",
    "BS BUSINESS ADMIN-MARKETING",
    "BS BUSINESS ADMIN-REAL ESTATE",
    "BS BUSINESS ADMIN-RISK MANAGEMENT INSUR",
    "BS BUSINESS ADMIN-SYSTEMS AND OPS MNGT",
    "BS BUSINESS ANALYTICS",
    "BS CELL AND MOLECULAR BIOLOGY",
    "BS CHEMISTRY",
    "BS CIVIL ENGINEERING",
    "BS COMPUTER ENGINEERING",
    "BS COMPUTER INFORMATION TECHNOLOGY",
    "BS COMPUTER SCIENCE",
    "BS CONSTRUCTION MANAGEMENT",
    "BS CONSUMER SCIENCES",
    "BS CONSUMER SCIENCES-FAM AND CONSUM SCI",
    "BS ECOLOGY AND EVOLUTIONARY BIOLOGY",
    "BS ELECTRICAL ENGINEERING",
    "BS ENGINEERING MANAGEMENT TECHNOLOGY",
    "BS ENVIRONMENTAL AND OCCUP HEALTH-INDUS",
    "BS ENVIRONMENTAL AND OCCUPATIONAL HEALTH",
    "BS FAM AND CONSUMER SCI-FAMILY STUDIES",
    "BS FASHION DESIGN AND MERCH-FASH DES PRO",
    "BS FASHION DESIGN AND MERCH-FASHION MERC",
    "BS FASHION DESIGN AND MERCH-TEXTILES",
    "BS GEOGRAPHIC INFORMATION SCIENCE",
    "BS GEOGRAPHY AND ENVIRONMENTAL STUDIES",
    "BS GEOLOGY",
    "BS GEOLOGY-GEOPHYSICS",
    "BS HEALTH ADMINISTRATION",
    "BS INFORMATION SYSTEMS-BUSINESS SYSTEMS",
    "BS INFORMATION SYSTEMS-COMPUTER INFO",
    "BS INFORMATION SYSTEMS-HEALTH SYSTEM",
    "BS INFORMATION SYSTEMS-SOFTWARE TECH",
    "BS INTERIOR DESIGN",
    "BS KINESIOLOGY SPORT STUDIES",
    "BS KINESIOLOGY-APPLIED FITNESS AND ACTIV",
    "BS KINESIOLOGY-DANCE",
    "BS KINESIOLOGY-EXERCISE SCIENCE",
    "BS KINESIOLOGY-PHYSICAL EDUCATION",
    "BS MANUFACTURING SYSTEMS ENGINEERING",
    "BS MARINE BIOLOGY",
    "BS MATHEMATICS",
    "BS MATHEMATICS-APPLIED MATHEMATICAL SCI",
    "BS MATHEMATICS-STATISTICS",
    "BS MECHANICAL ENGINEERING",
    "BS MICROBIOLOGY",
    "BS NUTRITION DEIT AND FOOD SCI-FOOD SCI",
    "BS NUTRITION DEIT AND FOOD SCI-NUTRI DIE",
    "BS PHYSICS",
    "BS PHYSICS-ASTROPHYSICS",
    "BS PUBLIC HEALTH",
    "BS RADIOLOGIC SCIENCES",
    "BS TOURISM HOSPITALITY REC MNGT",
    "BSN NURSING-ACCELERATED",
    "BSN NURSING-RN TO BSN",
    "DPT PHYSICAL THERAPY",
    "EDD EDUCATIONAL LEADERSHIP",
    "GC ADVANCED CERT IN TRANSDISCIPLINARY",
    "GC ADVANCED STUDY IN EDUCATIONAL THERAPY",
    "GC BILINGUAL AUTHORIZATION",
    "GC BUSINESS ADMINISTRATION",
    "GC CA TEACHERS OF ENGLISH LEARNERS",
    "GC CAREER EDUCATION AND COUNSELING",
    "GC CLEAR ADMINISTRATIVE SERVICES CRED",
    "GC COLLEGE AND CAREER CONN SEC CURRIC",
    "GC COMPLEX SYSTEMS CERTIFICATE",
    "GC CONSTRUCTION MANAGEMENT CERTIFICATE",
    "GC DIETETIC INTERNSHIP CERTIFICATE",
    "GC DUAL PRELIM SSC ED SPEC-MILD MOD EXT",
    "GC ENTREPRENEURSHIP AND INNOVATION MNGT",
    "GC ESSENTIALS OF PUBLIC ADMINISTRATION",
    "GC ETHNIC STUDIES-CHICANO-A STUDIES",
    "GC FOUNDATIONS OF ANTHROPOLOGICAL KNOWL",
    "GC FOUNDATIONS OF ARCHAEOLOGICAL KNOWLED",
    "GC GENERAL ED INDUCTION CRED MULTI SINGL",
    "GC HEALTH ADMINISTRATION CERTIFICATE",
    "GC HEALTH INFORMATICS ADMINISTRATION",
    "GC HEALTH SERVICES CREDENTIAL-SCHOOL NUR",
    "GC HOSPITALITY MANAGEMENT CERTIFICATE",
    "GC INFORMATION TECHNOLOGY CERTIFICATE",
    "GC INFORMATION TECHNOLOGY MANAGEMENT",
    "GC KNOWLEDGE MANAGEMENT",
    "GC LEAN SIX SIGMA",
    "GC MATHEMATICS SUBJ MATTER PROG FOR SSC",
    "GC MULTI SUBJ CRED-ACCELERATED COLLAB",
    "GC MULTI SUBJ CRED-INTEGRATED TEACHER",
    "GC MULTI SUBJ CRED-MULTI SUBJ UNI INTERN",
    "GC MULTI SUBJ CRED-TRADITIONAL PROGRAM",
    "GC MUSIC THERAPY CERTIFICATE",
    "GC NON-PROFIT SECTOR MANAGEMENT",
    "GC NURSE EDUCATOR CERTIFICATE",
    "GC PRELIM ADMINISTRATIVE SERVICES CRED",
    "GC PRELIM ED SPEC CRED-MILD MOD EXTENSIV",
    "GC PRELIM ED SPECIALIST CRED-DEAF HH",
    "GC PREP FOR ADVANCE STUDIES IN SPEECH",
    "GC PROGRAM EVALUATION IN ED AND ED RELAT",
    "GC PUBLIC HEALTH NURSE CERTIFICATE",
    "GC QUALITY MANAGEMENT CERTIFICATE",
    "GC READING AND LITERACY LEADERSHIP SPEC",
    "GC REAL ESTATE CERTIFICATE",
    "GC SPEECH-LANGUAGE PATHOLOGY SERVICES",
    "GC SSPC-ACCELERATED COLLAB TEACHER PREP",
    "GC SSPC-DUAL SS ED SPEC MILD MODERATE",
    "GC SSPC-INTEGRATED TEACHER CRED PROGRAM",
    "GC SSPC-SS UNIVERSITY INTERN PROGRAM",
    "GC SSPC-TRADITIONAL PROGRAM",
    "GC TEACHER INDUCTION ES-DEAF AND HEARING",
    "GC TEACHER INDUCTION ES-EARLY CHILDHOOD",
    "GC TEACHER INDUCTION ES-MILD MODERATE",
    "GC TEACHER INDUCTION GEN ED-MULTI SUBJ",
    "GC TEACHER INDUCTION GEN ED-SINGLE SUBJ",
    "MA ART EDUCATION",
    "MA CHICANO-CHICANA STUDIES",
    "MA COMMUNICATION STUDIES",
    "MA COUNSELING-EDUCATIONAL PSYCHOLOGY",
    "MA DIVERSE COMMUNITY DEVELOPMENT LEADERS",
    "MA EARLY CHILDHOOD EDUCATION PSYCHOLOGY",
    "MA EDUCATIONAL ADMINISTRATION",
    "MA EDUCATIONAL TECHNOLOGY",
    "MA EDUCATIONAL THERAPY",
    "MA ELEMENTARY ED-CIRRICULUM AND INSTRUCT",
    "MA ELEMENTARY ED-LANGUAGE AND LITERACY",
    "MA ELEMENTARY ED-MULTILINGUAL MULTICULT",
    "MA ENGLISH-CREATIVE WRITING",
    "MA ENGLISH-LITERATURE",
    "MA ENGLISH-RHETORIC AND COMPOSITION",
    "MA ENTERTAINMENT INDUSTRY MANAGEMENT",
    "MA GEOGRAPHY",
    "MA HIGHER EDUCATION LEADERSHIP",
    "MA HISTORY",
    "MA HUMANITIES",
    "MA INSTRUCTIONAL DESIGN",
    "MA LINGUISTICS",
    "MA MASS COMMUNICATION",
    "MA MULTICULTURAL AND MULTILINGUAL ED SEC",
    "MA MUSIC INDUSTRY ADMINISTRATION",
    "MA POLITICAL SCIENCE-AMERICAN POLITICS",
    "MA POLITICAL SCIENCE-GLOBAL POLITICS",
    "MA PSYCHOLOGICAL SCIENCE",
    "MA PSYCHOLOGY-CLINICAL FIELDWORK",
    "MA PSYCHOLOGY-CLINICAL RESEARCH",
    "MA PUBLIC ARCHAEOLOGY",
    "MA SECONDARY CURRICULUM AND INSTRUCTION",
    "MA SECONDARY ENGLISH EDUCATION",
    "MA SECONDARY MATHEMATICS EDUCATION",
    "MA SECONDARY SCIENCE EDUCATION",
    "MA SOCIOLOGY",
    "MA SPANISH",
    "MA SPECIAL ED-MILD MOD AND EXTENSIVE SUP",
    "MA SPECIAL EDUCATION-DEAF-HARD OF HEAR",
    "MA SPECIAL EDUCATION-EARLY CHILDHOOD SPC",
    "MA SUSTAINABILITY",
    "MA TEACHING ENGLISH AS A SECOND LANGUAGE",
    "MA THEATRE ARTS",
    "MA VISUAL ARTS",
    "MBA BUSINESS ADMINISTRATION",
    "MFA ART VISUAL ARTS",
    "MFA SCREENWRITING",
    "MHA HEALTH ADMINISTRATION",
    "MKM KNOWLEDGE MANAGEMENT",
    "MM MUSIC-COLLABORATIVE PIANO PERFORMANCE",
    "MM MUSIC-COMPOSITION",
    "MM MUSIC-CONDUCTING",
    "MM MUSIC-PERFORMANCE",
    "MPA PUBLIC ADMIN-GEOGRAPHICAL INFO SYS",
    "MPA PUBLIC ADMIN-HEALTH ADMIN",
    "MPA PUBLIC ADMIN-NON-PROFIT SECTOR MNGT",
    "MPA PUBLIC ADMIN-PERFORM MNGT PRODUCT",
    "MPA PUBLIC ADMIN-PUBLIC POLICY ANA MNGT",
    "MPA PUBLIC ADMIN-PUBLIC SECTOR MNGT LEAD",
    "MPACC PROFESSIONAL ACCOUNTANCY",
    "MPH PUBLIC HEALTH-APPLIED EPIDEMIOLOGY",
    "MPH PUBLIC HEALTH-COMMUNITY HEALTH EDUC",
    "MS APPLIED BEHAVIOR ANALYSIS",
    "MS ASSISTIVE TECHNOLOGY ENGINEERING",
    "MS ASSISTIVE TECHNOLOGY STUDIES HUM SERV",
    "MS ATHLETIC TRAINING",
    "MS BIOCHEMISTRY",
    "MS BIOLOGY",
    "MS BUSINESS ANALYTICS",
    "MS CHEMISTRY",
    "MS COMMUNICATIVE DISORDERS",
    "MS COMPUTER ENGINEERING",
    "MS COMPUTER SCIENCE",
    "MS CONSTRUCTION MANAGEMENT",
    "MS COUNSELING",
    "MS COUNSELING-COLLEGE COUNS AND STUDENT",
    "MS COUNSELING-LICENSED PRO CLINICAL COUN",
    "MS COUNSELING-SCHOOL COUNSELING",
    "MS ELECTRICAL ENGINEERING",
    "MS ENGINEERING MANAGEMENT",
    "MS ENGINEERING MANAGEMENT - DATA ANALYTI",
    "MS ENVIRONMEN AND OCCUP HEALTH-INDUS HYG",
    "MS ENVIRONMENTAL AND OCCUPATIONAL HEALTH",
    "MS FAM AND CONSUMER SCI-APPAREL DES MERC",
    "MS FAM AND CONSUMER SCI-CONSUM AFFAIRS",
    "MS GEOGRAPHIC INFORMATION SCIENCE",
    "MS GEOLOGY",
    "MS GEOLOGY-GEOPHYSICS",
    "MS HUMAN NUTRITION-DIETETIC INTERNSHIP",
    "MS HUMAN NUTRITION-HUMAN NUTRITON",
    "MS KINESIOLOGY",
    "MS MANUFACTURING SYSTEMS ENGINEERING",
    "MS MARRIAGE AND FAMILY THERAPY",
    "MS MATERIALS ENGINEERING",
    "MS MATHEMATICS-APPLIED MATHEMATICS",
    "MS MATHEMATICS-PURE MATHEMATICS",
    "MS MATHEMATICS-STATISTICS",
    "MS MECHANICAL ENGINEERING",
    "MS NURSING",
    "MS PHYSICS",
    "MS SCHOOL PSYCHOLOGY",
    "MS SOFTWARE ENGINEERING",
    "MS STRUCTURAL ENGINEERING",
    "MS TAXATION",
    "MS TOURISM HOSP AND REC MNGT-HOSP MNGT",
    "MS TOURISM HOSP AND REC MNGT-REC SPORT M",
    "MS TOURISM HOSP AND REC MNGT-TOUR MNGT",
    "MSW SOCIAL WORK",
    "MUP URBAN PLANNING",
    "THEATRE - ACTING AND DIRECTING OPTION",
    "THEATRE - DESIGN AND PRODUCTION OPTION",
    "THEATRE - THEATRE ARTS OPTION",
]

# ---------------------------------------------------------------------------
# Institution Registry — keyed by VA Facility Code
# ---------------------------------------------------------------------------
# Add new institutions here as they are scraped from the VA GI Bill Comparison Tool.

INSTITUTION_REGISTRY = {
    "11910105": {
        "name": "San Diego State University",
        "short": "SDSU",
        "programs": SDSU_WEAMS_PROGRAM_NAMES,
        "scraped_date": "2026-04-10",
    },
    "11918105": {
        "name": "California State University, Northridge",
        "short": "CSUN",
        "programs": CSUN_WEAMS_PROGRAM_NAMES,
        "scraped_date": "2026-04-10",
    },
}

# Default institution (backward compatibility)
DEFAULT_FACILITY_CODE = "11910105"


# Mapping of degree prefix to academic level
# Used for decision tree routing and validation
DEGREE_LEVEL_MAPPING = {
    # Undergraduate degrees
    "BA": "undergraduate",
    "BS": "undergraduate",
    "BFA": "undergraduate",
    "BM": "undergraduate",
    "BSN": "undergraduate",
    "AUD": "undergraduate",
    "THEATRE": "undergraduate",

    # Graduate degrees (Master's level)
    "MA": "graduate",
    "MS": "graduate",
    "MAT": "graduate",
    "MBA": "graduate",
    "MCP": "graduate",
    "MENG": "graduate",
    "MFA": "graduate",
    "MHA": "graduate",
    "MKM": "graduate",
    "MM": "graduate",
    "MPA": "graduate",
    "MPACC": "graduate",
    "MPH": "graduate",
    "MUP": "graduate",
    "MSW": "graduate",

    # Combined degrees (Master's level)
    "MBA-JD": "graduate",
    "MBA-MA": "graduate",
    "MPA-JD": "graduate",
    "MPA-MA": "graduate",
    "MPH-MA": "graduate",
    "MSW-JD": "graduate",
    "MSW-MPH": "graduate",

    # Doctoral degrees
    "PHD": "doctoral",
    "DNP": "doctoral",
    "DPT": "doctoral",
    "DrPH": "doctoral",
    "EDD": "doctoral",
    "EDS": "doctoral",

    # Graduate Certificates
    "GC": "graduate_certificate",

    # Special/Articulation
    "ARTICULATION": "special",
    "MULTI": "special",
}


def parse_weams_entry(name: str) -> Tuple[str, str]:
    """
    Parse a WEAMS program name into degree prefix and program name.

    Examples:
        "BA JOURNALISM" -> ("BA", "JOURNALISM")
        "BS COMPUTER SCIENCE" -> ("BS", "COMPUTER SCIENCE")
        "ARTICULATION AGREEMENT FOR TRANSFER" -> ("ARTICULATION", "AGREEMENT FOR TRANSFER")

    Args:
        name: A WEAMS program name string

    Returns:
        Tuple of (degree_prefix, program_name)
    """
    name = name.strip()
    parts = name.split(None, 1)

    if len(parts) == 1:
        return (parts[0], "")

    return (parts[0], parts[1])


def _normalize_program_string(program: str) -> str:
    """
    Normalize a program string for comparison.

    - Strip whitespace
    - Uppercase
    - Remove periods and extra spaces
    - Normalize hyphens and dashes

    Args:
        program: Raw program string from PeopleSoft or user input

    Returns:
        Normalized string
    """
    program = program.strip().upper()
    # Remove periods
    program = program.replace(".", "")
    # Normalize various dash characters to space
    program = program.replace("-", " ")
    program = program.replace("–", " ")
    program = program.replace("—", " ")
    # Remove excess whitespace
    program = " ".join(program.split())
    return program


def _extract_degree_and_subject(declared: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Extract degree type and subject from a declared program string.

    Handles formats like:
    - "Journalism (BA)" -> ("BA", "JOURNALISM")
    - "B.A. Journalism" -> ("BA", "JOURNALISM")
    - "BA Journalism" -> ("BA", "JOURNALISM")
    - "Computer Science, BS" -> ("BS", "COMPUTER SCIENCE")
    - "BS - Journalism" -> ("BS", "JOURNALISM")

    Args:
        declared: Program string from PeopleSoft ACAD_PLAN description

    Returns:
        Tuple of (degree_prefix, subject) or (None, None) if parsing fails
    """
    normalized = _normalize_program_string(declared)

    # Pattern 1: "Subject (DEGREE)" or "Subject (Degree)"
    # e.g., "Journalism (BA)" or "Computer Science (BS)"
    import re
    match = re.search(r'^(.+?)\s*\(([A-Z]+)\)$', normalized)
    if match:
        subject, degree = match.groups()
        return (degree.strip(), subject.strip())

    # Pattern 2: "DEGREE. Subject" or "Degree. Subject"
    # e.g., "B.A. Journalism" (already normalized to "BA JOURNALISM")
    words = normalized.split()
    known_degrees = set(DEGREE_LEVEL_MAPPING.keys())

    # Try first word as degree
    if words and words[0] in known_degrees:
        degree = words[0]
        subject = " ".join(words[1:]) if len(words) > 1 else ""
        return (degree, subject) if subject else (degree, None)

    # Try to find degree keyword anywhere in string
    for word in words:
        if word in known_degrees:
            # Extract subject as everything before the degree
            idx = words.index(word)
            subject_words = words[:idx] + words[idx+1:]
            subject = " ".join(subject_words) if subject_words else None
            return (word, subject) if subject else (word, None)

    return (None, None)


def _jaccard_similarity(set1: set, set2: set) -> float:
    """
    Calculate Jaccard similarity between two sets of words.

    Args:
        set1: First set of words
        set2: Second set of words

    Returns:
        Similarity score between 0 and 1
    """
    if not set1 and not set2:
        return 1.0

    intersection = len(set1 & set2)
    union = len(set1 | set2)

    return intersection / union if union > 0 else 0.0


def _fuzzy_match_score(declared: str, weams_entry: str) -> Tuple[float, str]:
    """
    Calculate a fuzzy match score between declared program and WEAMS entry.

    Uses keyword overlap (Jaccard-like similarity) on program names.

    Args:
        declared: Declared program string (normalized)
        weams_entry: WEAMS program string

    Returns:
        Tuple of (score, confidence_level) where score is 0-1 and confidence is
        "HIGH", "MEDIUM", or "LOW"
    """
    # Split into meaningful keywords (ignore common words)
    common_words = {"AND", "OR", "FOR", "OF", "IN", "THE", "A", "AN", "IS", "ARE"}

    declared_words = set(declared.split()) - common_words
    weams_words = set(_normalize_program_string(weams_entry).split()) - common_words

    similarity = _jaccard_similarity(declared_words, weams_words)

    # Determine confidence based on similarity score
    if similarity >= 0.75:
        confidence = "HIGH"
    elif similarity >= 0.50:
        confidence = "MEDIUM"
    else:
        confidence = "LOW"

    return (similarity, confidence)


def match_weams_program(declared_program: str, facility_code: str = None) -> Optional[Tuple[str, str]]:
    """
    Match a student's declared program against the WEAMS program list.

    Handles PeopleSoft format variations like "Journalism (BA)", "B.A. Journalism",
    "Computer Science", etc. and matches them to WEAMS format names like
    "BA JOURNALISM" or "BS COMPUTER SCIENCE".

    Matching strategy (in order):
    1. Exact match (after normalization)
    2. Degree + subject match: extract degree and subject, look for matching WEAMS entry
    3. Fuzzy keyword matching with similarity scoring

    Args:
        declared_program: Program name from PeopleSoft ACAD_PLAN description
        facility_code: VA Facility Code to determine which institution's programs to search.
                       If None, defaults to SDSU (11910105)

    Returns:
        Tuple of (matched_program_name, confidence_level) where:
        - matched_program_name is the WEAMS program string if found, None otherwise
        - confidence_level is "HIGH", "MEDIUM", "LOW", or "NOT_FOUND"
    """
    if not declared_program or not isinstance(declared_program, str):
        return (None, "NOT_FOUND")

    # Determine which institution's programs to search
    fc = facility_code or DEFAULT_FACILITY_CODE
    if fc not in INSTITUTION_REGISTRY:
        return (None, "NOT_FOUND")
    program_list = INSTITUTION_REGISTRY[fc]["programs"]

    normalized_declared = _normalize_program_string(declared_program)
    normalized_weams_list = [_normalize_program_string(p) for p in program_list]

    # Strategy 1: Exact match after normalization
    for original, normalized in zip(program_list, normalized_weams_list):
        if normalized == normalized_declared:
            return (original, "HIGH")

    # Strategy 2: Extract degree and subject, then match
    degree, subject = _extract_degree_and_subject(declared_program)

    if degree and subject:
        # Look for WEAMS entries starting with this degree and containing subject keywords
        # Split on both spaces and hyphens for better matching
        # e.g. "NURSING-ACCELERATED" -> {"NURSING", "ACCELERATED"}
        import re as _re
        subject_words = set(_re.split(r'[\s\-]+', subject))

        candidates = []
        for original, normalized in zip(program_list, normalized_weams_list):
            weams_degree, weams_subject = parse_weams_entry(original)

            if weams_degree == degree:
                # Check if subject keywords overlap (split hyphens too)
                weams_subject_words = set(_re.split(r'[\s\-]+', weams_subject))
                overlap = subject_words & weams_subject_words

                if overlap:
                    # Calculate overlap percentage
                    overlap_ratio = len(overlap) / len(subject_words)
                    candidates.append((original, overlap_ratio))

        if candidates:
            # Sort by overlap ratio, descending
            candidates.sort(key=lambda x: x[1], reverse=True)
            best_match, overlap_ratio = candidates[0]

            confidence = "HIGH" if overlap_ratio >= 0.8 else "MEDIUM"
            return (best_match, confidence)

    # Strategy 3: Fuzzy keyword matching
    best_score = 0.0
    best_match = None
    best_confidence = "LOW"

    for original in program_list:
        score, confidence = _fuzzy_match_score(normalized_declared, original)
        if score > best_score:
            best_score = score
            best_match = original
            best_confidence = confidence

    if best_score >= 0.40:  # Minimum threshold for fuzzy match
        return (best_match, best_confidence)

    return (None, "NOT_FOUND")
